import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingTop: 34, paddingBottom: 138 },
  journalListScroll: { paddingHorizontal: 20, paddingTop: 38, paddingBottom: 138 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 22 },
  headerIcon: { width: 46, height: 46, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 23, fontWeight: '900' },
  headerSubtitle: { fontSize: 12, marginTop: 2 },
  dashboardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 64, marginBottom: 24, paddingHorizontal: 2 },
  identity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10, minWidth: 0 },
  greeting: { fontSize: 16, fontWeight: '800' },
  nameText: { fontSize: 22, fontWeight: '900', marginTop: -2 },
  topActions: { flexDirection: 'row', alignItems: 'center', gap: 9, marginLeft: 10 },
  smallIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#FFFFFF88', alignItems: 'center', justifyContent: 'center' },
  iconBubble: { alignItems: 'center', justifyContent: 'center' },
  welcomeCard: { minHeight: 132, borderRadius: 25, borderWidth: 1, padding: 15, flexDirection: 'row', overflow: 'hidden', marginBottom: 12 },
  welcomeTitle: { fontSize: 18, fontWeight: '900' },
  welcomeArt: { width: 125, borderRadius: 30, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  progressCard: { borderRadius: 27, borderWidth: 1, padding: 20, flexDirection: 'row', alignItems: 'center', marginBottom: 12, minHeight: 125 },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardSectionTitle: { fontSize: 14, fontWeight: '900' },
  progressNumber: { fontSize: 31, fontWeight: '900', marginTop: 14 },
  smallText: { fontSize: 11, lineHeight: 16 },
  reminder: { borderRadius: 20, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  statCard: { flex: 1, borderRadius: 20, padding: 13, minHeight: 112 },
  statNumber: { fontSize: 24, fontWeight: '900', marginTop: 10 },
  statLabel: { fontSize: 9, marginTop: 2 },
  loopTitle: { fontSize: 13, fontWeight: '900', letterSpacing: 0.7, marginBottom: 9 },
  moduleCard: { width: '100%', borderRadius: 23, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 9 },
  moduleTitle: { fontSize: 15, fontWeight: '900', marginBottom: 2 },
  bottomNav: { position: 'absolute', left: 16, right: 16, bottom: 14, borderRadius: 30, borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', shadowColor: '#4B87B7', shadowOpacity: 0.16, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 10 },
  globalBottomNav: { height: 92, paddingHorizontal: 7 },
  journalBottomNav: { height: 92, paddingHorizontal: 7 },
  journalTabs: { flexDirection: 'row', width: '100%', borderRadius: 20, borderWidth: 1, padding: 4, marginBottom: 18 },
  journalTab: { flex: 1, minWidth: 0, height: 38, borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },
  journalTabText: { fontSize: 10, fontWeight: '900', textAlign: 'center' },
  journalSectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  newEntryTopButton: { minHeight: 42, borderRadius: 16, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  journalListCard: { width: '100%', minHeight: 104, borderRadius: 18, borderWidth: 1, padding: 8, marginBottom: 10, overflow: 'hidden' },
  journalListThumb: { width: 58, height: 58, borderRadius: 14 },
  journalListContent: { flex: 1, minWidth: 0, justifyContent: 'center' },
  journalListTopRow: { flexDirection: 'row', alignItems: 'center', minWidth: 0 },
  journalListTitle: { flex: 1, fontSize: 12, fontWeight: '900', marginRight: 4 },
  journalListDate: { fontSize: 8, marginTop: 1 },
  journalMoodPill: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 3, borderRadius: 10, paddingHorizontal: 6, paddingVertical: 3, marginTop: 4, backgroundColor: '#FFFFFFAA' },
  journalMoodText: { fontSize: 8, fontWeight: '900' },
  journalListPreview: { fontSize: 8, marginTop: 2 },
  journalListMainButton: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10, paddingRight: 36 },
  favoriteButton: { position: 'absolute', right: 10, top: 10, width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFFCC' },
  globalNavButton: { flex: 1, minWidth: 0, height: 80, alignItems: 'center', justifyContent: 'center', gap: 3, borderRadius: 22, paddingHorizontal: 2 },
  globalNavIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  navIconWrap: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  navButton: { flex: 1, minWidth: 0, height: 80, alignItems: 'center', justifyContent: 'center', gap: 2, borderRadius: 22, paddingHorizontal: 2 },
  navLabel: { fontSize: 11, fontWeight: '800', letterSpacing: 0.05, textAlign: 'center' },
  centerFab: { width: 62, height: 62, borderRadius: 31, alignItems: 'center', justifyContent: 'center', marginTop: -27, shadowColor: '#1767B7', shadowOpacity: 0.3, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
  ringOuter: { width: 86, height: 86, borderRadius: 43, borderWidth: 7, alignItems: 'center', justifyContent: 'center' },
  ringInner: { width: 68, height: 68, borderRadius: 34, alignItems: 'center', justifyContent: 'center' },
  ringScore: { fontSize: 17, fontWeight: '900' },
  ringLabel: { fontSize: 8 },
  cloud: { position: 'absolute', borderRadius: 100, opacity: 0.7 },
  cloud1: { width: 240, height: 95, top: 55, right: -70 },
  cloud2: { width: 170, height: 75, top: 125, left: -65 },
  cloud3: { width: 210, height: 80, top: 190, right: -90 },
  mountain: { position: 'absolute', top: 155, right: -30, width: 0, height: 0, borderLeftWidth: 120, borderRightWidth: 120, borderBottomWidth: 110, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#FFFFFF55' },
  mountainSmall: { position: 'absolute', top: 185, left: 80, width: 0, height: 0, borderLeftWidth: 80, borderRightWidth: 80, borderBottomWidth: 75, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#FFFFFF33' },
  journalComposer: { borderRadius: 26, borderWidth: 1, padding: 17, marginBottom: 13 },
  quickReflectionToggle: { minHeight: 68, borderRadius: 20, borderWidth: 1, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8, marginBottom: 2 },
  quickReflectionPanel: { borderRadius: 20, borderWidth: 1, padding: 12, marginTop: 8, marginBottom: 4 },
  plusSmall: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  fieldLabel: { fontSize: 12, fontWeight: '900', marginBottom: 7, marginTop: 10 },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  secondaryButton: { flex: 1, minHeight: 48, borderRadius: 18, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 },
  primaryButton: { flex: 1, minHeight: 48, borderRadius: 18, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 },
  buttonText: { fontSize: 13, fontWeight: '900' },
  buttonTextWhite: { color: '#fff', fontSize: 13, fontWeight: '900' },
  entryCountCard: { borderRadius: 24, borderWidth: 1, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 18 },
  emptyCard: { borderRadius: 25, borderWidth: 1, padding: 30, alignItems: 'center', marginTop: 8 },
  quickBackdrop: { flex: 1, backgroundColor: '#10233F88', justifyContent: 'flex-end' },
  quickModal: { width: '100%', maxHeight: '91%', borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 18 },
  quickHandle: { width: 42, height: 4, borderRadius: 3, backgroundColor: '#CBD4DF', alignSelf: 'center', marginBottom: 10 },
  quickTitleRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  quickTitle: { fontSize: 16, fontWeight: '900' },
  quickClose: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  quickSectionLabel: { fontSize: 11, fontWeight: '900', marginTop: 12, marginBottom: 7 },
  quickGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 8 },
  quickChoice: { width: '48.3%', minHeight: 62, borderRadius: 14, borderWidth: 1, padding: 8, flexDirection: 'row', alignItems: 'center', gap: 7 },
  quickChoiceText: { flex: 1, fontSize: 9, lineHeight: 13, fontWeight: '700' },
  quickInput: { minHeight: 76, borderRadius: 15, borderWidth: 1, padding: 11, fontSize: 11 },
  quickCounter: { textAlign: 'right', fontSize: 8, marginTop: 3 },
  fullEntryLink: { height: 30, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 8 },
  fullEntryLinkText: { fontSize: 10, fontWeight: '900' },
  entryCard: { width: '100%', marginBottom: 14, borderRadius: 20, overflow: 'hidden' },
  entryImage: { width: '100%', minHeight: 210, justifyContent: 'flex-end' },
  entryShade: { ...StyleSheet.absoluteFillObject, backgroundColor: '#1E4F7A30' },
  entryGlass: { margin: 14, borderRadius: 20, padding: 15, borderWidth: 1, minHeight: 118 },
  entryTitle: { fontSize: 17, fontWeight: '900', marginTop: 7 },
  searchBox: { borderRadius: 18, borderWidth: 1, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  input: { flex: 1, minHeight: 46, fontSize: 13 },
  inputBox: { minHeight: 50, borderRadius: 17, borderWidth: 1, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
  textInput: { minHeight: 52, borderRadius: 17, borderWidth: 1, paddingHorizontal: 14, fontSize: 14 },
  bodyInput: { minHeight: 170, borderRadius: 20, borderWidth: 1, padding: 14, fontSize: 14 },
  counter: { fontSize: 10, marginBottom: 6 },
  backgroundModeRow: { flexDirection: 'row', borderRadius: 16, padding: 4, marginTop: 16, gap: 4 },
  backgroundModeButton: { flex: 1, minHeight: 42, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 8 },
  backgroundModeText: { fontSize: 12, fontWeight: '800' },
  pickerSectionTitle: { fontSize: 14, fontWeight: '900', marginTop: 16, marginBottom: 2 },
  patternCategoryRow: { gap: 8, paddingVertical: 12 },
  patternCategoryButton: { minWidth: 62, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 13 },
  patternGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 2 },
  patternTile: { width: '31.5%', height: 170, borderRadius: 16, overflow: 'hidden', backgroundColor: '#FFFFFF', alignSelf: 'stretch', alignItems: 'stretch' },
  patternTileImage: { width: '100%', height: '100%', alignSelf: 'stretch' },
  patternCheck: { position: 'absolute', top: 7, right: 7, width: 27, height: 27, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  patternNamePill: { position: 'absolute', left: 5, right: 5, bottom: 5, backgroundColor: '#FFFFFFDD', borderRadius: 9, paddingHorizontal: 6, paddingVertical: 5 },
  inlineBackgroundChooser: { borderRadius: 22, borderWidth: 1, padding: 14, marginTop: 16, marginBottom: 12 },
  selectedBackgroundHint: { borderRadius: 13, padding: 9, marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 7 },
  backgroundSelector: { borderRadius: 20, borderWidth: 1, minHeight: 82, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 10 },
  solidColorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 18 },
  solidColorTile: { width: '47%', minHeight: 118, borderRadius: 22, padding: 12, justifyContent: 'flex-end', alignItems: 'flex-start', overflow: 'hidden' },
  solidColorNamePill: { backgroundColor: '#FFFFFFCC', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 },
  solidColorName: { color: '#4B5563', fontWeight: '800', fontSize: 12 },
  solidColorCheck: { position: 'absolute', top: 9, right: 9, width: 29, height: 29, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  exploreColorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 12 },
  exploreColorCard: { width: '47%', minHeight: 105, borderRadius: 22, padding: 12, justifyContent: 'flex-end', alignItems: 'flex-start' },
  exploreColorLabel: { backgroundColor: '#FFFFFFCC', borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5 },
  explorePatternsSection: { borderRadius: 22, borderWidth: 1, padding: 14, marginTop: 20 },
  patternSectionLabel: { fontSize: 13, fontWeight: '900', marginBottom: 8 },
  explorePatternGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 10 },
  explorePatternTile: { width: '31.5%', height: 150, borderRadius: 16, borderWidth: 1, overflow: 'hidden', backgroundColor: '#FFFFFF', alignSelf: 'stretch', alignItems: 'stretch' },
  explorePatternImage: { width: '100%', height: '100%', alignSelf: 'stretch' },
  explorePatternNamePill: { position: 'absolute', left: 5, right: 5, bottom: 5, backgroundColor: '#FFFFFFDD', borderRadius: 9, paddingHorizontal: 6, paddingVertical: 5 },
  affirmationIntro: { borderRadius: 22, borderWidth: 1, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  affirmationCard: { borderRadius: 18, borderWidth: 1, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  affirmationNumber: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  affirmationNumberText: { fontWeight: '900', fontSize: 12 },
  affirmationText: { flex: 1, fontSize: 14, lineHeight: 20, fontWeight: '600' },
  selectorImage: { width: 64, height: 64, borderRadius: 16 },
  photoBox: { marginTop: 12, minHeight: 74, borderRadius: 18, borderWidth: 1, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', gap: 5 },
  photoPreview: { width: '100%', height: 150 },
  photoChangePill: { position: 'absolute', left: 10, bottom: 10, borderRadius: 14, paddingHorizontal: 9, paddingVertical: 6, backgroundColor: '#00000088', flexDirection: 'row', alignItems: 'center', gap: 5 },
  photoChangeText: { color: '#fff', fontSize: 10, fontWeight: '800' },
  moodRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 7 },
  moodItem: { alignItems: 'center', width: 62 },
  moodCircle: { width: 50, height: 50, borderRadius: 25, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  moodLabel: { fontSize: 9, marginTop: 4 },
  modalBackdrop: { flex: 1, backgroundColor: '#0A315655', justifyContent: 'flex-end' },
  bgModal: { maxHeight: '88%', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 17 },
  modalTitle: { fontSize: 19, fontWeight: '900' },
  closeButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#EEF6FF', alignItems: 'center', justifyContent: 'center' },
  filterChip: { paddingHorizontal: 14, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  bgGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12, paddingBottom: 8 },
  bgTile: { width: '31.5%', aspectRatio: 1, borderRadius: 18, overflow: 'hidden', position: 'relative' },
  bgTileImage: { width: '100%', height: '100%' },
  checkOverlay: { position: 'absolute', top: 5, right: 5, width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  readScreen: { flex: 1 },
  readTop: { paddingHorizontal: 20, paddingTop: 28, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  readRound: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#173F6B88', alignItems: 'center', justifyContent: 'center' },
  readDate: { color: '#fff', fontSize: 11, fontWeight: '800', backgroundColor: '#173F6B88', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 16 },
  readScroll: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 125 },
  readGlass: { borderRadius: 25, borderWidth: 1, padding: 18, marginTop: 18 },
  readTitle: { color: '#fff', fontSize: 24, fontWeight: '900' },
  readMood: { alignSelf: 'flex-start', marginTop: 10, borderRadius: 18, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: '#FFFFFF22', flexDirection: 'row', alignItems: 'center', gap: 5 },
  readContent: { color: '#fff', fontSize: 15, lineHeight: 24, marginTop: 18 },
  readMoodItem: { alignItems: 'center', width: 57 },
  readMoodCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FFFFFF20', alignItems: 'center', justifyContent: 'center' },
  attachedPhoto: { width: '100%', height: 180, borderRadius: 18, marginTop: 14 },
  segment: { flexDirection: 'row', width: '100%', backgroundColor: '#FFFFFF99', borderRadius: 22, padding: 4, marginBottom: 14, overflow: 'hidden' },
  segmentActive: { flex: 1, minWidth: 0, borderRadius: 18, minHeight: 44, paddingHorizontal: 8, alignItems: 'center', justifyContent: 'center' },
  segmentItem: { flex: 1, minWidth: 0, minHeight: 44, paddingHorizontal: 8, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  segmentActiveText: { color: '#fff', fontSize: 13, fontWeight: '900', textAlign: 'center' },
  segmentText: { fontSize: 13, fontWeight: '800', textAlign: 'center' },
  calendarCard: { borderRadius: 24, borderWidth: 1, padding: 14 },
  calendarArrowButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  calendarMonthTitle: { fontSize: 17, fontWeight: '900' },
  weekRow: { flexDirection: 'row', width: '100%', marginTop: 14 },
  weekText: { flex: 1, minWidth: 0, textAlign: 'center', fontSize: 10, fontWeight: '800' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  dayCell: { width: '14.2857%', height: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 23, flexShrink: 0 },
  calendarDayNumber: { width: 24, textAlign: 'center', fontSize: 12, lineHeight: 16, fontWeight: '800' },
  dot: { width: 5, height: 5, borderRadius: 3, marginTop: 3 },
  calendarHint: { marginTop: 10, minHeight: 36, borderRadius: 14, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 7 },
  calendarPreviewBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.48)', justifyContent: 'center', paddingHorizontal: 20 },
  calendarPreviewCard: { width: '100%', maxHeight: '82%', borderRadius: 26, borderWidth: 1, padding: 16, overflow: 'hidden' },
  calendarPreviewImage: { width: '100%', height: 150, marginTop: 14, borderRadius: 18, overflow: 'hidden', justifyContent: 'flex-end' },
  calendarPreviewImageShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(255,255,255,0.10)' },
  calendarPreviewGlass: { margin: 10, borderRadius: 15, padding: 10, backgroundColor: 'rgba(255,255,255,0.82)' },
  calendarPreviewTitle: { color: '#4B1833', fontSize: 16, lineHeight: 20, fontWeight: '900' },
  calendarPreviewMood: { color: '#8A5870', fontSize: 11, marginTop: 2, fontWeight: '800' },
  calendarPreviewContent: { fontSize: 14, lineHeight: 21, marginTop: 14 },
  emptyPreview: { alignItems: 'center', justifyContent: 'center', paddingVertical: 28 },
  reflectionCard: { borderRadius: 24, borderWidth: 1, padding: 14, marginTop: 12 },
  tipCard: { borderRadius: 19, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 9 },
  explorePattern: { width: '31.5%', aspectRatio: 1, borderRadius: 18, overflow: 'hidden' },
  addTaskCard: { borderRadius: 22, borderWidth: 1, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  circleAdd: { width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  primarySmall: { paddingHorizontal: 15, height: 42, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  taskCard: { borderRadius: 20, borderWidth: 1, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 9 },
  checkCircle: { width: 37, height: 37, borderRadius: 19, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  studyHero: { borderRadius: 23, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  studyCard: { borderRadius: 23, borderWidth: 1, padding: 14 },
  stepInput: { minHeight: 80, borderRadius: 15, borderWidth: 1, padding: 10, textAlignVertical: 'top', fontSize: 13 },
  profileHero: { borderRadius: 26, borderWidth: 1, padding: 25, alignItems: 'center', marginBottom: 15 },
  profileName: { fontSize: 24, fontWeight: '900', marginTop: 10 },
  themeRow: { flexDirection: 'row', gap: 10 },
  themeGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 10 },
  themeChoice: { width: '31.8%', minHeight: 100, borderRadius: 20, borderWidth: 1, alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 8 },
  darkToggleRow: { borderRadius: 20, borderWidth: 1, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 6 },
  darkToggleTrack: { width: 52, height: 30, borderRadius: 15, padding: 3, justifyContent: 'center' },
  darkToggleKnob: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#fff' },
});
